name: graph
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.11.14
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - fastapi==0.121.3
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain-core==1.0.7
      - langgraph==1.0.3
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.2.9
      - langsmith==0.4.44
      - orjson==3.11.4
      - ormsgpack==1.12.0
      - packaging==25.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - python-multipart==0.0.20
      - pyyaml==6.0.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - sniffio==1.3.1
      - starlette==0.50.0
      - tenacity==9.1.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - xxhash==3.6.0
      - zstandard==0.25.0
      - pandas==2.2.0
      - openai==1.58.1
prefix: /data/project/atwoddl/Anaconda3/envs/graph
